Dev
stepyndriyy/TpPatternProject pull request #4
Opened 2020-05-07 00:11 UTC by stepyndriyy

Готовая к проверке версия

2020-05-10 14:40 UTC, akhtyamovpavel requested changes
Добрый день!

Стало намного лучше, однако появилось пара замечаний по коду и игре:
- [x] игра падает, если передать меньше 4 координат
- [ ] сборка проекта осуществляется через include-ы cpp-шных файлов, что плохо
- [x] некоторые замечания указаны по ходу ревью

Повышаю оценку по первой части задания в 9, во второй - до восьми. Жду исправления замечаний и новую версию!

2020-05-10 14:40 UTC, akhtyamovpavel commented on ARCHITECTURE.md
> +        3. Command
Для третьей части не хватает обоснования отсутствия CoR, Visitor, Observer

2020-05-10 14:40 UTC, akhtyamovpavel commented on ARCHITECTURE.md
> +    - Декоратор: В силу не улучшаемости юнитов этот паттерн не имеет смысла
неулучшаемости пишется слитно

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/buildings/adapted_barracks.cpp
> +    if (dir == 'l')
Лучше сделать словарь, чтобы не было if-а

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/buildings/barracks
> +#include "barracks.cpp"
Не очень хорошо включать cpp-шные файлы

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/buildings/barracks.h
> +class Barracks : public virtual Entity {
Зачем здесь virtual?

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/commands/command_attack.cpp
> +        std::cout << "there is no units(\n";
Лучше кидать исключения

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/commands/command_attack.cpp
> +    if (enemy == nullptr) {
if !enemy

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/game.h
> +    add_unit(0, Cell(1, 1), new Swordsman(1));
Что означает 1 и 2 в параметрах конструктора?

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/game.h
> +        }
Советую вынести в отдельную функцию

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/map/gamemap.cpp
> +}
Не превращается ли `GameMap` в GoD-object?

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/map/gamemap.cpp
> +    std::queue<Cell> q;
Однобуквенные переменные - это плохо

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/map/gamemap.cpp
> +int GameMap::real_dist(const Cell &from, const Cell &to) {
Стоит посмотреть в сторону паттерна стратегии, поскольку явно игра делает много чего

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/map/gamemap.cpp
> +        for (Cell diff : near) {
В чем смысл переменной `near`?

2020-05-10 14:40 UTC, akhtyamovpavel commented on src/map/gamemap.cpp
> +            if ((dist[next.y][next.x] != -1) || (!is_cell_empty(next)))
Лишние скобки

2020-05-10 14:40 UTC, akhtyamovpavel approved these changes

2020-05-13 18:40 UTC, stepyndriyy commented
Исправил большинство пометок.
Оставил includ'ы cpp файлов, на момент коммита не научился исправлять этого.
Решил не использовать паттерн стратегия, т.к. класс gamemap должен отвечать за поиск путей, других причин не понял.

2020-05-17 17:43 UTC, akhtyamovpavel commented
@stepyndriyy, к сожалению, если не уметь этого исправлять, то мы можем снять баллы за технические задания, поскольку это явно проверяется на них.

Про поиск путей - это алгоритм, при этом необязательно bfs, поэтому жду обертку в виде паттерна стратегия. Как только будет применен этот паттерн, будет поставлена оценка за третью часть

2020-05-18 09:43 UTC, stepyndriyy commented
исправил все недочеты, использовал паттерн стратегия

2020-10-05 20:07 UTC, merged